version: '3.3'

volumes:
  pg_project:

services:

  mcbconnector-pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=mcbconnector
      - POSTGRES_USER=mcbconnector
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5440}:5432
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/barry/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
